<x-app-layout>
    <div class="grid grid-cols-4">
        <button>1</button>
        <button>2</button>
        <button>3</button>
        <button>4</button>
        <button>5</button>
        <button>6</button>
        <button>7</button>
        <button>8</button>
        <button>9</button>
        <button>0</button>
        <button>/</button>
        <button>*</button>
        <button>+</button>
        <button>-</button>
        <button>=</button>
    </div>
</x-app-layout>
